	.include	"macros.inc"

	.SEGMENT	"BOOTTXT1"
;	.ORG	$BD80
	StrAtasciiToANTIC	"          DATASOFT (R) PRESENTS         "
	StrAtasciiToANTIC	"              "
	StrAtasciiToANTIC	"       |  Alternate Reality (R) |       "
	StrAtasciiToANTIC	"       |                        |       "
	StrAtasciiToANTIC	"       |      The Dungeon       |       "
	StrAtasciiToANTIC	"              "
	StrAtasciiToANTIC	"          (c) Copyright 1987 by         "
	StrAtasciiToANTIC	"          IntelliCreations Inc.         "
	StrAtasciiToANTIC	"           All rights reserved.         "
	StrAtasciiToANTIC	"            Alternate Reality           "
	StrAtasciiToANTIC	"      is a registered trademark of      "
	StrAtasciiToANTIC	"        Paradise Programming Inc.       "
	StrAtasciiToANTIC	"               Datasoft                 "
	StrAtasciiToANTIC	"      is a registered trademark of      "
	StrAtasciiToANTIC	"          IntelliCreations Inc.         "
	StrAtasciiToANTIC	"                                   V2.1 "
