	.include	"macros.inc"

	.SEGMENT	"BOOTTXT2"
;	.ORG	$BD80

	StrAtasciiToANTIC	"          DATASOFT (R) PRESENTS         "
	StrAtasciiToANTIC	"              "
	StrAtasciiToANTIC	"       |  Alternate Reality (R) |       "
	StrAtasciiToANTIC	"       |                        |       "
	StrAtasciiToANTIC	"       |      The Dungeon       |       "
	StrAtasciiToANTIC	"              "
	StrAtasciiToANTIC	"           (p) Pirated 1987 by          "
	StrAtasciiToANTIC	"          †††ŸÔıÚ†Œ·ÌÂ†»ÂÚÂ††††         "
	StrAtasciiToANTIC	"                                        "
	StrAtasciiToANTIC	"   Alternate Reality is one of the few  "
	StrAtasciiToANTIC	"  pieces of software to be designed for "
	StrAtasciiToANTIC	"    a handful of paying customers.      "
	StrAtasciiToANTIC	"   Your rampant distribution of this    "
	StrAtasciiToANTIC	" product will assist software developers"
	StrAtasciiToANTIC	" in abandoning this machine altogether. "
	StrAtasciiToANTIC	"           -Have a nice day-            "
