
;		.ORG	$96F0

		.BYTE	$02,$00,$fd,$fd,$11,$11,$07,$11,$11,$11,$11,$11,$11,$11,$07,$11 ; |................|
		.BYTE	$11,$00,$a4,$a4,$97,$97,$9e,$97,$97,$97,$97,$97,$97,$97,$9e,$97 ; |................|
		.BYTE	$97,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$af,$6a,$aa,$aa,$aa,$aa,$aa ; |..........j.....|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$ab,$da,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$f6,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$bd,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$bd,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$af,$6a,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$af,$6a,$aa,$aa ; |...j.........j..|
		.BYTE	$aa,$aa,$aa,$aa,$ab,$da,$aa,$aa,$aa,$aa,$af,$6a,$aa,$aa,$ab,$da ; |...........j....|
		.BYTE	$ab,$da,$aa,$aa,$aa,$aa,$aa,$f6,$aa,$aa,$aa,$aa,$ab,$da,$aa,$aa ; |................|
		.BYTE	$aa,$f6,$aa,$f6,$aa,$aa,$aa,$aa,$aa,$bd,$aa,$aa,$aa,$aa,$aa,$f6 ; |................|
		.BYTE	$aa,$aa,$aa,$bd,$aa,$bd,$aa,$aa,$aa,$aa,$aa,$af,$6a,$aa,$aa,$aa ; |............j...|
		.BYTE	$aa,$bd,$aa,$aa,$aa,$af,$6a,$af,$6a,$aa,$aa,$aa,$aa,$ab,$da,$aa ; |......j.j.......|
		.BYTE	$aa,$aa,$aa,$af,$6a,$aa,$aa,$ab,$da,$ab,$da,$aa,$aa,$aa,$aa,$aa ; |....j...........|
		.BYTE	$f6,$aa,$aa,$aa,$aa,$ab,$da,$aa,$aa,$aa,$f6,$aa,$f6,$aa,$aa,$af ; |................|
		.BYTE	$6a,$aa,$bd,$aa,$aa,$aa,$aa,$aa,$f6,$aa,$aa,$aa,$bd,$aa,$bd,$aa ; |j...............|
		.BYTE	$aa,$ab,$da,$aa,$af,$6a,$aa,$aa,$aa,$aa,$bd,$aa,$aa,$aa,$af,$6a ; |.....j.........j|
		.BYTE	$af,$6a,$aa,$aa,$f6,$af,$6b,$da,$aa,$aa,$aa,$aa,$af,$6a,$aa,$aa ; |.j....k......j..|
		.BYTE	$ab,$da,$ab,$da,$aa,$aa,$bd,$ab,$da,$aa,$aa,$aa,$aa,$af,$6b,$da ; |..............k.|
		.BYTE	$aa,$aa,$aa,$f6,$aa,$f6,$aa,$aa,$af,$6a,$f6,$aa,$aa,$aa,$aa,$ab ; |.........j......|
		.BYTE	$da,$f6,$aa,$aa,$aa,$bd,$aa,$bd,$aa,$aa,$ab,$da,$bd,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$f6,$bd,$aa,$aa,$aa,$af,$6a,$af,$6a,$aa,$aa,$f6,$af,$6a ; |........j.j....j|
		.BYTE	$ab,$da,$aa,$aa,$bd,$af,$6a,$aa,$aa,$ab,$da,$ab,$da,$aa,$aa,$bd ; |......j.........|
		.BYTE	$ab,$da,$aa,$f6,$aa,$aa,$af,$6b,$da,$aa,$bd,$aa,$f6,$aa,$f6,$aa ; |.......k........|
		.BYTE	$aa,$af,$6a,$f6,$aa,$bd,$aa,$aa,$ab,$da,$f6,$aa,$af,$6a,$bd,$aa ; |..j..........j..|
		.BYTE	$bd,$aa,$aa,$ab,$da,$bd,$aa,$af,$6a,$aa,$aa,$f6,$aa,$aa,$ab,$da ; |........j.......|
		.BYTE	$af,$6a,$af,$aa,$aa,$aa,$f6,$aa,$aa,$ab,$da,$aa,$aa,$aa,$aa,$aa ; |.j..............|
		.BYTE	$aa,$f6,$ab,$da,$aa,$aa,$aa,$aa,$bd,$aa,$aa,$aa,$f6,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$bd,$aa,$f6,$aa,$aa,$aa,$aa,$af,$6a,$aa,$aa,$bd,$aa ; |...........j....|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$af,$6a,$bd,$aa,$aa,$aa,$aa,$ab,$da,$aa,$aa ; |......j.........|
		.BYTE	$af,$6a,$aa,$aa,$aa,$aa,$aa,$ab,$da,$af,$6a,$aa,$aa,$aa,$aa,$f6 ; |.j........j.....|
		.BYTE	$aa,$aa,$ab,$da,$aa,$aa,$aa,$aa,$aa,$aa,$f6,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$f6,$aa,$aa,$aa,$aa,$aa,$aa,$bd,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$bd,$aa,$aa,$aa,$aa,$aa,$aa,$af,$6a ; |...............j|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$f6,$af,$6a,$aa,$aa,$aa,$aa,$aa ; |..........j.....|
		.BYTE	$ab,$da,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$bd,$ab,$da,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$f6,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$af,$6a,$f6,$aa ; |.............j..|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$bd,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$ab,$da ; |................|
		.BYTE	$bd,$aa,$aa,$aa,$aa,$aa,$aa,$af,$6a,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |........j.......|
		.BYTE	$aa,$f6,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$ab,$da,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$bd,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$f6,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$af,$6a,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$bd,$aa ; |......j.........|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$ab,$da,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$bd,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$f6,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$af,$6a,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$bd,$aa,$aa,$af ; |....j...........|
		.BYTE	$6a,$aa,$aa,$aa,$aa,$ab,$da,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$af,$6a ; |j..............j|
		.BYTE	$aa,$ab,$da,$aa,$aa,$aa,$aa,$aa,$f6,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$ab,$da,$aa,$aa,$f6,$aa,$aa,$aa,$aa,$aa,$bd,$aa,$bd,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$f6,$aa,$aa,$bd,$aa,$aa,$aa,$aa,$aa,$af,$6a,$af,$6a ; |.............j.j|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$af,$6a,$aa,$aa,$aa,$aa,$ab,$da ; |.........j......|
		.BYTE	$ab,$da,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$ab,$da,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$f6,$aa,$f6,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$f6,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$bd,$aa,$bd,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$bd ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$af,$6a,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |......j.........|
		.BYTE	$aa,$af,$6a,$aa,$aa,$aa,$aa,$ab,$da,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |..j.............|
		.BYTE	$aa,$aa,$aa,$ab,$da,$aa,$aa,$aa,$aa,$aa,$f6,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$f6,$aa,$aa,$aa,$aa,$aa,$bd,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$bd,$aa,$aa,$aa,$f6,$aa,$af,$6a ; |...............j|
		.BYTE	$aa,$ab,$da,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$af,$6a,$aa,$aa,$bd,$aa ; |...........j....|
		.BYTE	$ab,$da,$aa,$aa,$f6,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$ab,$da,$aa,$aa ; |................|
		.BYTE	$af,$6a,$aa,$f6,$aa,$aa,$bd,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$f6 ; |.j..............|
		.BYTE	$aa,$aa,$ab,$da,$aa,$aa,$aa,$aa,$af,$6a,$aa,$aa,$aa,$aa,$ab,$da ; |.........j......|
		.BYTE	$aa,$bd,$aa,$aa,$aa,$f6,$aa,$aa,$aa,$aa,$ab,$da,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$f6,$aa,$af,$6a,$aa,$aa,$bd,$aa,$aa,$aa,$aa,$aa,$f6,$aa,$aa ; |....j...........|
		.BYTE	$aa,$aa,$aa,$bd,$aa,$ab,$da,$aa,$aa,$af,$6a,$aa,$aa,$aa,$aa,$bd ; |..........j.....|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$af,$6a,$aa,$aa,$aa,$aa,$ab,$da,$aa,$aa,$aa ; |......j.........|
		.BYTE	$aa,$af,$6a,$aa,$aa,$aa,$aa,$ab,$da,$aa,$aa,$aa,$aa,$aa,$f6,$aa ; |..j.............|
		.BYTE	$aa,$aa,$aa,$ab,$da,$aa,$aa,$aa,$aa,$aa,$f6,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$bd,$aa,$aa,$aa,$aa,$aa,$f6,$aa,$aa,$aa,$aa,$aa,$bd,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$af,$6a,$aa,$aa,$aa,$aa,$bd,$aa,$aa,$aa,$aa,$aa,$af,$6a ; |...j...........j|
		.BYTE	$aa,$aa,$aa,$aa,$ab,$da,$aa,$aa,$aa,$f6,$af,$6a,$aa,$aa,$aa,$aa ; |...........j....|
		.BYTE	$ab,$da,$aa,$aa,$aa,$aa,$aa,$f6,$aa,$aa,$aa,$bd,$ab,$da,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$f6,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$af,$6a,$f6 ; |..............j.|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$ab ; |................|
		.BYTE	$da,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$f6,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$bd,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$af,$6a,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |.......j........|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$ab,$da,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$b6,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$ad,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$ab,$6a,$aa,$ab,$aa ; |............j...|
		.BYTE	$ab,$6a,$aa,$aa,$aa,$da,$aa,$aa,$ea,$aa,$da,$da,$aa,$aa,$b6,$aa ; |.j..............|
		.BYTE	$aa,$ba,$aa,$b6,$b6,$aa,$ba,$ad,$aa,$aa,$ae,$aa,$ad,$ad,$aa,$ae ; |................|
		.BYTE	$ab,$6a,$aa,$aa,$aa,$ab,$6b,$6a,$ab,$aa,$aa,$aa,$b6,$aa,$aa,$da ; |.j....kj........|
		.BYTE	$da,$aa,$da,$aa,$aa,$ad,$aa,$aa,$b6,$b6,$aa,$b6,$aa,$da,$ab,$6a ; |...............j|
		.BYTE	$ab,$ad,$ad,$aa,$ad,$aa,$b6,$aa,$ea,$aa,$eb,$6b,$aa,$ab,$6a,$ad ; |...........k..j.|
		.BYTE	$aa,$aa,$aa,$ba,$da,$aa,$aa,$da,$ab,$6a,$aa,$aa,$ae,$ba,$aa,$aa ; |.........j......|
		.BYTE	$aa,$aa,$da,$aa,$aa,$ab,$aa,$aa,$aa,$aa,$ad,$b6,$aa,$aa,$aa,$ea ; |................|
		.BYTE	$aa,$aa,$aa,$ab,$6d,$aa,$aa,$aa,$ba,$aa,$aa,$aa,$aa,$da,$aa,$aa ; |....m...........|
		.BYTE	$aa,$ae,$aa,$aa,$aa,$aa,$b6,$aa,$aa,$aa,$aa,$b6,$aa,$aa,$aa,$ad ; |................|
		.BYTE	$aa,$b6,$aa,$aa,$ad,$aa,$aa,$aa,$ab,$6a,$ad,$aa,$aa,$ab,$6b,$aa ; |.........j....k.|
		.BYTE	$aa,$aa,$ea,$ab,$6a,$aa,$aa,$da,$ea,$aa,$aa,$aa,$aa,$da,$aa,$aa ; |....j...........|
		.BYTE	$ba,$aa,$aa,$aa,$aa,$aa,$b6,$aa,$aa,$ae,$aa,$aa,$aa,$aa,$aa,$ae ; |................|
		.BYTE	$aa,$ae,$ab,$aa,$aa,$aa,$aa,$aa,$ab,$aa,$ab,$aa,$ea,$ad,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$ea,$aa,$ea,$aa,$ab,$6a,$aa,$aa,$da,$ba,$aa,$b6,$aa,$aa ; |.......j........|
		.BYTE	$da,$aa,$aa,$b6,$aa,$aa,$ad,$aa,$aa,$b6,$aa,$aa,$ad,$aa,$aa,$ab ; |................|
		.BYTE	$6a,$aa,$ad,$aa,$aa,$ab,$6a,$aa,$aa,$da,$aa,$db,$6a,$aa,$aa,$ea ; |j.....j.....j...|
		.BYTE	$aa,$aa,$aa,$aa,$b6,$ea,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$ad,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$ab,$6a,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |.......j........|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$a0,$aa,$aa,$aa,$aa,$a0,$aa,$aa,$aa,$aa,$a0,$b6,$aa,$aa,$aa ; |................|
		.BYTE	$a0,$ad,$aa,$ba,$a6,$a0,$ab,$6a,$aa,$ad,$a0,$aa,$aa,$aa,$ab,$60 ; |.......j.......`|
		.BYTE	$aa,$ab,$aa,$aa,$e0,$ba,$aa,$ea,$aa,$a0,$ae,$aa,$ba,$aa,$a0,$ab ; |................|
		.BYTE	$aa,$aa,$aa,$a0,$aa,$aa,$aa,$aa,$a0,$aa,$aa,$aa,$aa,$a0,$ae,$a9 ; |................|
		.BYTE	$aa,$ae,$a0,$ab,$aa,$6a,$ab,$a0,$aa,$aa,$da,$aa,$a0,$aa,$aa,$ba ; |.....j..........|
		.BYTE	$aa,$a0,$aa,$aa,$aa,$aa,$a0,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$55 ; |...............U|
		.BYTE	$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55 ; |UUUUUUUUUUUUUUUU|
		.BYTE	$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55 ; |UUUUUUUUUUUUUUUU|
		.BYTE	$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55 ; |UUUUUUUUUUUUUUUU|
		.BYTE	$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55 ; |UUUUUUUUUUUUUUUU|
		.BYTE	$55,$55,$55,$55,$55,$55,$55,$5d,$55,$55,$55,$55,$55,$55,$55,$55 ; |UUUUUUU]UUUUUUUU|
		.BYTE	$55,$55,$55,$55,$55,$55,$55,$55,$75,$57,$55,$55,$55,$55,$55,$55 ; |UUUUUUUUuWUUUUUU|
		.BYTE	$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$d5,$55,$aa,$aa,$aa,$55 ; |UUUUUUUUUU.U...U|
		.BYTE	$55,$55,$55,$55,$55,$55,$55,$55,$55,$56,$aa,$aa,$55,$55,$aa,$aa ; |UUUUUUUUUV..UU..|
		.BYTE	$aa,$aa,$95,$55,$55,$55,$55,$55,$55,$56,$aa,$aa,$aa,$aa,$55,$55 ; |...UUUUUUV....UU|
		.BYTE	$aa,$af,$aa,$aa,$aa,$a9,$55,$55,$55,$55,$6a,$af,$aa,$af,$aa,$aa ; |......UUUUj.....|
		.BYTE	$55,$55,$aa,$ab,$ea,$aa,$aa,$aa,$aa,$a5,$5a,$aa,$aa,$ab,$ea,$ab ; |UU........Z.....|
		.BYTE	$ea,$aa,$55,$55,$aa,$aa,$fa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |..UU............|
		.BYTE	$fa,$aa,$fa,$aa,$55,$55,$aa,$aa,$be,$aa,$aa,$aa,$aa,$aa,$fa,$aa ; |....UU..........|
		.BYTE	$aa,$aa,$be,$aa,$be,$aa,$55,$55,$ea,$aa,$af,$aa,$aa,$aa,$aa,$aa ; |......UU........|
		.BYTE	$be,$aa,$aa,$aa,$af,$aa,$af,$aa,$55,$55,$fa,$af,$ab,$ea,$aa,$aa ; |........UU......|
		.BYTE	$aa,$aa,$af,$aa,$aa,$aa,$ab,$ea,$ab,$ea,$55,$55,$be,$ab,$ea,$aa ; |..........UU....|
		.BYTE	$aa,$aa,$aa,$af,$ab,$ea,$aa,$aa,$aa,$fa,$aa,$fa,$55,$55,$af,$aa ; |............UU..|
		.BYTE	$fa,$aa,$aa,$aa,$aa,$ab,$ea,$fa,$aa,$aa,$aa,$be,$aa,$be,$55,$55 ; |..............UU|
		.BYTE	$ab,$ea,$be,$aa,$aa,$aa,$aa,$aa,$fa,$be,$aa,$aa,$aa,$af,$aa,$af ; |................|
		.BYTE	$55,$55,$aa,$fa,$af,$aa,$ab,$ea,$aa,$aa,$be,$af,$aa,$aa,$aa,$ab ; |UU..............|
		.BYTE	$ea,$ab,$55,$55,$aa,$be,$ab,$ea,$aa,$fa,$aa,$aa,$af,$ab,$ea,$aa ; |..UU............|
		.BYTE	$be,$aa,$fa,$aa,$55,$55,$aa,$af,$aa,$fa,$aa,$be,$aa,$aa,$ab,$ea ; |....UU..........|
		.BYTE	$fa,$aa,$af,$aa,$be,$aa,$55,$55,$aa,$ab,$ea,$be,$aa,$af,$aa,$aa ; |......UU........|
		.BYTE	$aa,$fa,$aa,$aa,$ab,$ea,$af,$aa,$55,$55,$aa,$aa,$fa,$aa,$aa,$ab ; |........UU......|
		.BYTE	$ea,$aa,$aa,$aa,$aa,$aa,$aa,$fa,$ab,$ea,$55,$55,$aa,$aa,$be,$aa ; |..........UU....|
		.BYTE	$aa,$aa,$fa,$aa,$aa,$aa,$aa,$aa,$aa,$be,$aa,$fa,$55,$55,$aa,$aa ; |............UU..|
		.BYTE	$af,$aa,$aa,$aa,$be,$aa,$aa,$aa,$aa,$aa,$aa,$af,$aa,$be,$55,$55 ; |..............UU|
		.BYTE	$aa,$aa,$ab,$ea,$aa,$aa,$af,$aa,$aa,$aa,$aa,$aa,$aa,$ab,$ea,$af ; |................|
		.BYTE	$55,$55,$aa,$aa,$aa,$fa,$aa,$aa,$ab,$ea,$aa,$aa,$aa,$aa,$aa,$aa ; |UU..............|
		.BYTE	$fa,$aa,$55,$55,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$fa,$aa,$aa,$aa,$aa ; |..UU............|
		.BYTE	$aa,$aa,$be,$aa,$55,$55,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$be,$aa,$aa ; |....UU..........|
		.BYTE	$aa,$aa,$aa,$aa,$af,$aa,$55,$55,$aa,$aa,$aa,$aa,$aa,$aa,$fa,$af ; |......UU........|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$ab,$ea,$55,$55,$aa,$aa,$aa,$aa,$aa,$aa ; |........UU......|
		.BYTE	$be,$ab,$ea,$aa,$aa,$aa,$aa,$aa,$aa,$fa,$55,$55,$aa,$aa,$aa,$aa ; |..........UU....|
		.BYTE	$aa,$aa,$af,$aa,$fa,$aa,$aa,$aa,$aa,$aa,$aa,$be,$55,$55,$aa,$aa ; |............UU..|
		.BYTE	$aa,$aa,$aa,$aa,$ab,$ea,$be,$aa,$aa,$aa,$aa,$aa,$aa,$af,$55,$55 ; |..............UU|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$fa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$ab ; |................|
		.BYTE	$55,$55,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$be,$aa,$aa,$aa,$aa,$aa,$aa ; |UU..............|
		.BYTE	$aa,$aa,$55,$55,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$af,$aa,$aa,$aa,$aa ; |..UU............|
		.BYTE	$aa,$aa,$aa,$aa,$55,$55,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$ab,$ea,$aa ; |....UU..........|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$55,$55,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |......UU........|
		.BYTE	$fa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$55,$55,$aa,$aa,$aa,$aa,$aa,$aa ; |........UU......|
		.BYTE	$aa,$aa,$be,$aa,$aa,$af,$aa,$aa,$aa,$aa,$55,$55,$ea,$aa,$aa,$aa ; |..........UU....|
		.BYTE	$aa,$aa,$aa,$aa,$af,$aa,$aa,$ab,$ea,$aa,$aa,$aa,$55,$55,$fa,$aa ; |............UU..|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$ab,$ea,$aa,$aa,$fa,$aa,$aa,$aa,$55,$55 ; |..............UU|
		.BYTE	$be,$aa,$be,$aa,$aa,$aa,$aa,$aa,$aa,$fa,$aa,$aa,$be,$aa,$aa,$aa ; |................|
		.BYTE	$55,$55,$af,$aa,$af,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$af,$aa ; |UU..............|
		.BYTE	$aa,$aa,$55,$55,$ab,$ea,$ab,$ea,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |..UU............|
		.BYTE	$ab,$ea,$aa,$aa,$55,$55,$aa,$fa,$aa,$fa,$aa,$aa,$aa,$aa,$aa,$aa ; |....UU..........|
		.BYTE	$aa,$aa,$aa,$fa,$aa,$aa,$55,$55,$aa,$be,$aa,$be,$aa,$aa,$aa,$aa ; |......UU........|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$be,$aa,$aa,$55,$55,$aa,$af,$aa,$aa,$aa,$aa ; |........UU......|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$af,$aa,$aa,$55,$55,$aa,$ab,$ea,$aa ; |..........UU....|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$ab,$ea,$aa,$55,$55,$aa,$aa ; |............UU..|
		.BYTE	$fa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$fa,$aa,$55,$55 ; |..............UU|
		.BYTE	$aa,$aa,$be,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$be,$aa ; |................|
		.BYTE	$55,$55,$fa,$aa,$af,$aa,$aa,$ab,$ea,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |UU..............|
		.BYTE	$af,$aa,$55,$55,$be,$aa,$ab,$ea,$aa,$aa,$fa,$aa,$aa,$aa,$aa,$aa ; |..UU............|
		.BYTE	$aa,$aa,$ab,$ea,$55,$55,$af,$aa,$aa,$fa,$aa,$aa,$be,$aa,$aa,$aa ; |....UU..........|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$fa,$55,$55,$ab,$ea,$aa,$aa,$aa,$aa,$af,$aa ; |......UU........|
		.BYTE	$aa,$aa,$aa,$aa,$ab,$ea,$aa,$be,$55,$55,$aa,$fa,$aa,$aa,$aa,$aa ; |........UU......|
		.BYTE	$ab,$ea,$aa,$aa,$aa,$aa,$aa,$fa,$aa,$af,$55,$55,$aa,$be,$aa,$aa ; |..........UU....|
		.BYTE	$aa,$aa,$aa,$fa,$aa,$aa,$aa,$aa,$aa,$be,$aa,$ab,$55,$55,$aa,$af ; |............UU..|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$be,$aa,$aa,$aa,$aa,$aa,$af,$aa,$aa,$55,$55 ; |..............UU|
		.BYTE	$aa,$ab,$ea,$aa,$aa,$aa,$aa,$af,$aa,$aa,$aa,$aa,$aa,$ab,$ea,$aa ; |................|
		.BYTE	$55,$55,$aa,$aa,$fa,$aa,$aa,$aa,$aa,$ab,$ea,$aa,$aa,$aa,$aa,$aa ; |UU..............|
		.BYTE	$fa,$aa,$55,$55,$aa,$aa,$be,$aa,$aa,$aa,$aa,$aa,$fa,$aa,$aa,$aa ; |..UU............|
		.BYTE	$aa,$aa,$be,$aa,$55,$55,$aa,$aa,$af,$aa,$aa,$aa,$aa,$aa,$be,$aa ; |....UU..........|
		.BYTE	$aa,$aa,$aa,$aa,$af,$aa,$55,$55,$aa,$aa,$ab,$ea,$aa,$aa,$aa,$aa ; |......UU........|
		.BYTE	$af,$aa,$aa,$aa,$aa,$aa,$ab,$ea,$55,$55,$aa,$aa,$aa,$fa,$aa,$aa ; |........UU......|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$fa,$55,$55,$aa,$aa,$aa,$aa ; |..........UU....|
		.BYTE	$aa,$aa,$aa,$a5,$5a,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$55,$55,$aa,$aa ; |....Z.......UU..|
		.BYTE	$aa,$aa,$aa,$a5,$55,$55,$55,$55,$6a,$aa,$aa,$aa,$aa,$aa,$55,$55 ; |....UUUUj.....UU|
		.BYTE	$aa,$aa,$aa,$aa,$55,$55,$55,$55,$55,$55,$55,$56,$aa,$aa,$aa,$aa ; |....UUUUUUUV....|
		.BYTE	$55,$55,$aa,$aa,$a5,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$6a ; |UU...UUUUUUUUUUj|
		.BYTE	$aa,$aa,$55,$57,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55 ; |..UWUUUUUUUUUUUU|
		.BYTE	$55,$55,$55,$55,$d5,$5d,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55 ; |UUUU.]UUUUUUUUUU|
		.BYTE	$55,$55,$55,$55,$55,$55,$75,$55,$55,$55,$55,$55,$55,$55,$55,$55 ; |UUUUUUuUUUUUUUUU|
		.BYTE	$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55 ; |UUUUUUUUUUUUUUUU|
		.BYTE	$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55 ; |UUUUUUUUUUUUUUUU|
		.BYTE	$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55 ; |UUUUUUUUUUUUUUUU|
		.BYTE	$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55 ; |UUUUUUUUUUUUUUUU|
		.BYTE	$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55 ; |UUUUUUUUUUUUUUUU|
		.BYTE	$55,$75,$55,$55,$55,$55,$55,$55,$55,$5d,$5a,$aa,$a5,$55,$55,$55 ; |UuUUUUUUU]Z..UUU|
		.BYTE	$5a,$aa,$a5,$5a,$ba,$aa,$aa,$55,$aa,$ba,$ba,$a5,$5a,$ae,$aa,$aa ; |Z..Z...U....Z...|
		.BYTE	$aa,$aa,$ae,$ae,$a5,$5e,$bb,$aa,$aa,$aa,$aa,$ab,$ab,$a5,$5b,$ae ; |.....^........[.|
		.BYTE	$aa,$aa,$ba,$aa,$aa,$ea,$e5,$5a,$eb,$aa,$aa,$ae,$aa,$aa,$ba,$b5 ; |.......Z........|
		.BYTE	$5a,$ba,$ea,$ea,$ab,$aa,$ab,$ae,$a5,$5a,$ae,$aa,$ba,$aa,$ea,$aa ; |Z........Z......|
		.BYTE	$eb,$a5,$5a,$ab,$aa,$ae,$aa,$aa,$aa,$ba,$e5,$5a,$aa,$ea,$ab,$aa ; |..Z........Z....|
		.BYTE	$aa,$aa,$ae,$b5,$5a,$aa,$aa,$aa,$ea,$aa,$aa,$ab,$a5,$5a,$aa,$aa ; |....Z........Z..|
		.BYTE	$ae,$ba,$aa,$aa,$aa,$e5,$5a,$aa,$aa,$ab,$ae,$aa,$aa,$aa,$b5,$5a ; |......Z........Z|
		.BYTE	$aa,$aa,$aa,$ea,$aa,$aa,$aa,$a5,$5a,$aa,$aa,$aa,$ba,$aa,$aa,$aa ; |........Z.......|
		.BYTE	$a5,$5a,$aa,$aa,$aa,$ae,$aa,$ba,$aa,$a5,$5e,$aa,$aa,$aa,$ab,$aa ; |.Z........^.....|
		.BYTE	$ae,$aa,$a5,$5b,$ab,$aa,$aa,$aa,$ea,$ab,$aa,$a5,$5a,$ea,$ea,$aa ; |...[........Z...|
		.BYTE	$aa,$aa,$aa,$ea,$a5,$5a,$ba,$aa,$aa,$aa,$aa,$aa,$ba,$a5,$5a,$ae ; |.....Z........Z.|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$ae,$a5,$5e,$ab,$aa,$aa,$aa,$aa,$aa,$ab,$a5 ; |.......^........|
		.BYTE	$5b,$aa,$ea,$ae,$aa,$aa,$aa,$aa,$e5,$5a,$ea,$aa,$ab,$aa,$aa,$aa ; |[........Z......|
		.BYTE	$ea,$b5,$5a,$ba,$aa,$aa,$ea,$aa,$aa,$ba,$a5,$5a,$ae,$aa,$aa,$ba ; |..Z........Z....|
		.BYTE	$aa,$aa,$ae,$a5,$5a,$ab,$aa,$aa,$ae,$aa,$aa,$ab,$a5,$5a,$aa,$ea ; |....Z........Z..|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$e5,$5a,$aa,$aa,$aa,$55,$aa,$aa,$aa,$a5,$5a ; |......Z...U....Z|
		.BYTE	$aa,$a5,$55,$55,$55,$5a,$aa,$a5,$75,$55,$55,$55,$55,$55,$55,$55 ; |..UUUZ..uUUUUUUU|
		.BYTE	$5d,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55 ; |]UUUUUUUUUUUUUUU|
		.BYTE	$55,$55,$55,$55,$55,$55,$55,$50,$6a,$55,$55,$56,$90,$6a,$aa,$aa ; |UUUUUUUPjUUV.j..|
		.BYTE	$aa,$90,$6a,$aa,$aa,$aa,$90,$6a,$aa,$ab,$aa,$90,$6e,$aa,$aa,$ea ; |..j....j....n...|
		.BYTE	$90,$6b,$ab,$aa,$ba,$90,$6a,$ea,$ea,$ae,$90,$6a,$ba,$ba,$ab,$90 ; |.k....j....j....|
		.BYTE	$6a,$aa,$ae,$aa,$90,$6a,$aa,$ab,$aa,$90,$6e,$aa,$aa,$ea,$90,$6b ; |j....j....n....k|
		.BYTE	$aa,$aa,$aa,$90,$6a,$ea,$aa,$aa,$90,$6a,$ba,$aa,$aa,$90,$6a,$aa ; |....j....j....j.|
		.BYTE	$aa,$aa,$90,$69,$55,$55,$56,$90,$55,$55,$55,$55,$50,$ff,$ff,$ff ; |...iUUV.UUUUP...|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$00,$00,$00,$00,$00 ; |................|
		.BYTE	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ; |................|
		.BYTE	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ; |................|
		.BYTE	$00,$00,$00,$00,$00,$00,$00,$00,$00,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$ab,$da,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$f6,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$bd,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$af,$6a,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |.j..............|
		.BYTE	$aa,$aa,$ab,$da,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$f6,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$f6,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$bd,$aa,$aa,$aa,$aa,$aa,$aa,$bd,$aa,$f6,$aa,$aa,$aa,$aa,$af,$6a ; |...............j|
		.BYTE	$aa,$aa,$af,$6a,$aa,$aa,$aa,$af,$6a,$af,$6a,$bd,$aa,$aa,$aa,$aa ; |...j....j.j.....|
		.BYTE	$ab,$da,$aa,$aa,$ab,$da,$aa,$aa,$aa,$ab,$da,$ab,$da,$af,$6a,$aa ; |..............j.|
		.BYTE	$aa,$aa,$aa,$f6,$aa,$aa,$aa,$f6,$aa,$aa,$aa,$aa,$f6,$aa,$f6,$ab ; |................|
		.BYTE	$da,$aa,$aa,$aa,$aa,$bd,$aa,$aa,$aa,$bd,$aa,$aa,$aa,$aa,$bd,$aa ; |................|
		.BYTE	$bd,$aa,$f6,$aa,$aa,$aa,$aa,$af,$6a,$aa,$aa,$af,$6a,$aa,$aa,$aa ; |........j...j...|
		.BYTE	$af,$6a,$af,$6a,$bd,$aa,$aa,$aa,$aa,$ab,$da,$aa,$aa,$ab,$da,$aa ; |.j.j............|
		.BYTE	$aa,$aa,$ab,$da,$ab,$da,$af,$6a,$aa,$aa,$aa,$aa,$f6,$aa,$aa,$aa ; |.......j........|
		.BYTE	$f6,$aa,$aa,$aa,$aa,$f6,$aa,$aa,$ab,$da,$aa,$aa,$aa,$aa,$bd,$aa ; |................|
		.BYTE	$f6,$aa,$bd,$aa,$aa,$aa,$aa,$bd,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$af,$6a,$bd,$aa,$af,$6a,$aa,$aa,$aa,$af,$6a,$aa,$aa,$aa,$aa,$aa ; |.j...j....j.....|
		.BYTE	$aa,$aa,$ab,$da,$af,$6a,$ab,$da,$aa,$aa,$aa,$ab,$da,$aa,$aa,$aa ; |.....j..........|
		.BYTE	$aa,$aa,$af,$fe,$aa,$f6,$ab,$da,$aa,$f6,$aa,$aa,$aa,$aa,$f6,$aa ; |................|
		.BYTE	$aa,$aa,$bf,$fe,$ff,$ff,$aa,$bd,$aa,$f6,$aa,$bd,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$bd,$aa,$aa,$aa,$ff,$ff,$ff,$ff,$ea,$af,$6a,$bd,$aa,$aa,$aa,$aa ; |..........j.....|
		.BYTE	$aa,$aa,$af,$6a,$aa,$ab,$ff,$ff,$ff,$7f,$ea,$ab,$da,$af,$6a,$aa ; |...j..........j.|
		.BYTE	$aa,$aa,$aa,$aa,$ab,$da,$af,$ff,$ff,$7f,$f5,$5f,$ff,$fa,$f6,$ab ; |..........._....|
		.BYTE	$da,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$bf,$ff,$fd,$7f,$f4,$1f,$ff,$fe ; |................|
		.BYTE	$aa,$aa,$f6,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$bf,$ff,$fd,$5f,$d4,$1f ; |............._..|
		.BYTE	$ff,$ff,$aa,$aa,$bd,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$bf,$5f,$f5,$1f ; |............._..|
		.BYTE	$d0,$1f,$f5,$ff,$aa,$aa,$af,$6a,$aa,$aa,$aa,$aa,$aa,$aa,$ff,$55 ; |.......j.......U|
		.BYTE	$f4,$1f,$d0,$1f,$55,$7f,$aa,$aa,$ab,$da,$aa,$aa,$aa,$aa,$aa,$aa ; |....U...........|
		.BYTE	$ff,$41,$74,$17,$50,$1d,$41,$7f,$aa,$aa,$aa,$f6,$aa,$aa,$aa,$aa ; |.At.P.A.........|
		.BYTE	$aa,$aa,$fd,$40,$54,$07,$40,$15,$01,$ff,$fa,$aa,$aa,$bd,$aa,$aa ; |...@T.@.........|
		.BYTE	$aa,$aa,$aa,$aa,$fd,$40,$00,$07,$40,$00,$05,$ff,$fe,$aa,$aa,$af ; |.....@..@.......|
		.BYTE	$6a,$bd,$aa,$aa,$aa,$bf,$ff,$40,$00,$05,$40,$00,$07,$ff,$ff,$aa ; |j......@..@.....|
		.BYTE	$aa,$aa,$aa,$af,$6a,$aa,$aa,$ff,$ff,$40,$00,$00,$00,$00,$17,$ff ; |....j....@......|
		.BYTE	$ff,$ea,$aa,$aa,$aa,$ab,$da,$aa,$aa,$ff,$ff,$50,$00,$00,$00,$00 ; |...........P....|
		.BYTE	$1f,$f5,$7f,$ea,$aa,$aa,$aa,$aa,$f6,$aa,$aa,$fd,$ff,$d0,$00,$00 ; |................|
		.BYTE	$00,$00,$1f,$54,$5f,$ea,$aa,$aa,$aa,$aa,$bd,$aa,$aa,$fd,$57,$d0 ; |...T_.........W.|
		.BYTE	$00,$00,$00,$00,$15,$40,$1f,$ea,$aa,$aa,$aa,$aa,$af,$6a,$aa,$fd ; |.....@.......j..|
		.BYTE	$05,$50,$00,$00,$00,$00,$00,$00,$5f,$ea,$aa,$aa,$aa,$aa,$ab,$da ; |.P......_.......|
		.BYTE	$aa,$fd,$00,$00,$00,$00,$00,$00,$00,$00,$7f,$fa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$ab,$fd,$00,$00,$00,$00,$00,$00,$00,$01,$7f,$fe,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$af,$fd,$40,$00,$00,$00,$00,$00,$00,$01,$ff,$ff ; |......@.........|
		.BYTE	$af,$6a,$aa,$ab,$da,$aa,$bf,$ff,$40,$00,$00,$00,$00,$00,$00,$01 ; |.j......@.......|
		.BYTE	$ff,$ff,$ab,$da,$aa,$aa,$f6,$aa,$ff,$ff,$50,$00,$00,$00,$00,$00 ; |..........P.....|
		.BYTE	$00,$01,$57,$ff,$aa,$f6,$aa,$aa,$bd,$aa,$ff,$ff,$d0,$00,$00,$00 ; |..W.............|
		.BYTE	$00,$00,$00,$00,$07,$ff,$aa,$bd,$aa,$aa,$af,$6a,$ff,$d7,$d0,$00 ; |...........j....|
		.BYTE	$00,$00,$00,$00,$00,$00,$05,$ff,$ea,$af,$6a,$aa,$ab,$da,$ff,$55 ; |..........j....U|
		.BYTE	$50,$00,$00,$00,$00,$00,$00,$00,$01,$ff,$ea,$ab,$da,$aa,$aa,$aa ; |P...............|
		.BYTE	$ff,$40,$00,$00,$00,$00,$00,$00,$00,$00,$01,$7f,$ea,$aa,$aa,$aa ; |.@..............|
		.BYTE	$aa,$aa,$ff,$40,$00,$00,$00,$00,$00,$00,$00,$00,$01,$7f,$ea,$aa ; |...@............|
		.BYTE	$aa,$aa,$aa,$aa,$ff,$40,$00,$00,$00,$00,$00,$00,$00,$00,$05,$ff ; |.....@..........|
		.BYTE	$ea,$aa,$aa,$aa,$aa,$ab,$ff,$40,$00,$00,$00,$00,$00,$00,$00,$00 ; |.......@........|
		.BYTE	$57,$ff,$ea,$bd,$aa,$aa,$aa,$af,$ff,$40,$00,$00,$00,$00,$00,$00 ; |W........@......|
		.BYTE	$00,$00,$7f,$ff,$ea,$af,$6a,$aa,$aa,$bf,$fd,$40,$00,$00,$00,$00 ; |......j....@....|
		.BYTE	$00,$00,$00,$00,$57,$ff,$fa,$aa,$aa,$bd,$aa,$bf,$f5,$00,$00,$00 ; |....W...........|
		.BYTE	$00,$00,$00,$00,$00,$00,$05,$7f,$fe,$aa,$aa,$af,$6a,$bf,$d4,$00 ; |............j...|
		.BYTE	$00,$00,$00,$00,$00,$00,$00,$00,$00,$57,$ff,$aa,$aa,$ab,$da,$bf ; |.........W......|
		.BYTE	$d0,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$05,$ff,$aa,$aa,$aa ; |................|
		.BYTE	$f6,$bf,$d4,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$01,$7f,$aa ; |................|
		.BYTE	$aa,$aa,$bd,$af,$f5,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ; |................|
		.BYTE	$7f,$aa,$aa,$aa,$af,$6f,$fd,$40,$00,$00,$00,$00,$00,$00,$00,$00 ; |.....o.@........|
		.BYTE	$00,$01,$7f,$aa,$aa,$af,$6a,$ab,$ff,$54,$00,$00,$00,$00,$00,$00 ; |......j..T......|
		.BYTE	$00,$00,$00,$01,$ff,$aa,$aa,$ab,$da,$ab,$ff,$f4,$00,$00,$00,$00 ; |................|
		.BYTE	$00,$00,$00,$00,$00,$05,$ff,$aa,$aa,$aa,$f6,$af,$ff,$54,$00,$00 ; |.............T..|
		.BYTE	$00,$00,$00,$00,$00,$00,$00,$17,$fe,$aa,$aa,$aa,$bd,$af,$f5,$40 ; |...............@|
		.BYTE	$00,$00,$00,$00,$00,$00,$00,$00,$00,$1f,$fe,$aa,$aa,$aa,$aa,$bf ; |................|
		.BYTE	$d4,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$17,$fe,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$bf,$d0,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$05,$ff,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$bf,$50,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$01 ; |....P...........|
		.BYTE	$ff,$aa,$aa,$aa,$aa,$bf,$40,$00,$00,$00,$00,$00,$00,$00,$00,$00 ; |......@.........|
		.BYTE	$00,$01,$7f,$af,$6a,$aa,$aa,$bf,$50,$00,$00,$00,$00,$00,$00,$00 ; |....j...P.......|
		.BYTE	$00,$00,$00,$00,$7f,$ab,$da,$aa,$aa,$bf,$d0,$00,$00,$00,$00,$00 ; |................|
		.BYTE	$00,$00,$00,$00,$00,$00,$7f,$aa,$f6,$aa,$aa,$bf,$d0,$00,$00,$00 ; |................|
		.BYTE	$00,$00,$00,$00,$00,$00,$00,$01,$7f,$aa,$aa,$aa,$aa,$af,$d4,$00 ; |................|
		.BYTE	$00,$00,$00,$00,$00,$00,$00,$00,$00,$01,$ff,$aa,$aa,$aa,$aa,$af ; |................|
		.BYTE	$f4,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$01,$ff,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$af,$f4,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$05,$fe,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$ab,$f5,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$17 ; |................|
		.BYTE	$fe,$aa,$aa,$aa,$aa,$ab,$fd,$00,$00,$00,$00,$00,$00,$00,$00,$00 ; |................|
		.BYTE	$00,$1f,$fa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$ae,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$ab,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$ea,$aa,$aa,$aa,$aa,$ad,$aa,$aa,$ba,$ba,$da,$aa,$ab,$6a,$ab ; |..............j.|
		.BYTE	$6a,$aa,$ae,$ae,$b6,$aa,$aa,$da,$aa,$da,$aa,$ab,$ab,$ad,$aa,$aa ; |j...............|
		.BYTE	$b6,$aa,$b6,$aa,$aa,$ea,$ab,$6a,$aa,$ad,$ae,$ad,$aa,$aa,$ba,$aa ; |.......j........|
		.BYTE	$aa,$aa,$ab,$6b,$ab,$6a,$aa,$ae,$aa,$ab,$ef,$fa,$da,$ea,$da,$aa ; |...k.j..........|
		.BYTE	$ab,$aa,$af,$ff,$fe,$b6,$ba,$aa,$aa,$aa,$ab,$ff,$ff,$7f,$ee,$ae ; |................|
		.BYTE	$aa,$aa,$aa,$af,$fd,$fd,$7f,$fa,$ab,$aa,$aa,$aa,$af,$5d,$74,$75 ; |.............]tu|
		.BYTE	$fa,$aa,$ea,$aa,$aa,$af,$44,$74,$11,$fe,$aa,$ba,$ba,$aa,$ff,$40 ; |......Dt.......@|
		.BYTE	$10,$07,$ff,$aa,$aa,$ae,$aa,$ff,$40,$00,$07,$d7,$ea,$aa,$ab,$aa ; |........@.......|
		.BYTE	$f5,$40,$00,$01,$47,$ea,$aa,$aa,$aa,$f4,$00,$00,$00,$1f,$ea,$aa ; |.@..G...........|
		.BYTE	$aa,$ab,$f4,$00,$00,$00,$1f,$fb,$6a,$ad,$af,$f4,$00,$00,$00,$07 ; |........j.......|
		.BYTE	$fa,$da,$ab,$6f,$54,$00,$00,$00,$01,$fe,$b6,$aa,$af,$40,$00,$00 ; |...oT........@..|
		.BYTE	$00,$01,$fe,$aa,$aa,$af,$40,$00,$00,$00,$05,$fe,$aa,$aa,$bf,$40 ; |......@........@|
		.BYTE	$00,$00,$00,$07,$fe,$ba,$ba,$fd,$00,$00,$00,$00,$01,$7f,$aa,$ae ; |................|
		.BYTE	$fd,$00,$00,$00,$00,$00,$1f,$aa,$ab,$bd,$40,$00,$00,$00,$00,$1f ; |..........@.....|
		.BYTE	$aa,$b6,$bf,$d0,$00,$00,$00,$00,$1f,$aa,$ad,$bf,$40,$00,$00,$00 ; |............@...|
		.BYTE	$00,$7f,$aa,$aa,$fd,$00,$00,$00,$00,$00,$1f,$aa,$aa,$f4,$00,$00 ; |................|
		.BYTE	$00,$00,$00,$1f,$ba,$aa,$f4,$00,$00,$00,$00,$00,$1f,$ae,$aa,$bd ; |................|
		.BYTE	$00,$00,$00,$00,$00,$1f,$aa,$aa,$bd,$00,$00,$00,$00,$00,$1f,$aa ; |................|
		.BYTE	$aa,$bd,$00,$00,$00,$00,$00,$7e,$aa,$aa,$aa,$aa,$aa,$a0,$ab,$aa ; |.......~........|
		.BYTE	$aa,$ba,$a0,$aa,$ea,$aa,$ae,$a0,$aa,$ba,$aa,$ab,$a0,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$a0,$aa,$af,$ff,$ea,$a0,$aa,$bf,$ff,$ea,$a0,$aa,$bc,$33,$fa ; |..............3.|
		.BYTE	$a0,$ba,$f0,$03,$fa,$a0,$aa,$c0,$00,$3e,$a0,$bb,$c0,$00,$0e,$e0 ; |.........>......|
		.BYTE	$ab,$00,$00,$0e,$a0,$af,$c0,$00,$3f,$a0,$bf,$00,$00,$03,$a0,$ab ; |........?.......|
		.BYTE	$00,$00,$0f,$a0,$af,$c0,$00,$03,$a0,$af,$00,$00,$03,$a0,$ab,$c0 ; |................|
		.BYTE	$00,$0f,$a0,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ; |................|
		.BYTE	$49,$55,$10,$15,$0c,$73,$db,$bd,$f8,$c1,$e7,$8f,$1b,$63,$88,$80 ; |IU...s.......c..|
		.BYTE	$49,$55,$10,$15,$0c,$23,$8b,$bd,$f8,$c1,$e7,$8f,$1b,$63,$88,$80 ; |IU...#.......c..|
		.BYTE	$49,$55,$10,$15,$0c,$73,$db,$bd,$f8,$c1,$e7,$8f,$1b,$63,$88,$80 ; |IU...s.......c..|
		.BYTE	$49,$55,$10,$15,$0c,$73,$db,$bd,$f8,$c1,$e7,$8f,$1b,$63,$88,$80 ; |IU...s.......c..|
		.BYTE	$49,$55,$10,$15,$0c,$73,$db,$bd,$f8,$c1,$e7,$8f,$1b,$63,$88,$80 ; |IU...s.......c..|
		.BYTE	$49,$55,$10,$15,$0c,$73,$db,$bd,$f8,$c1,$e7,$8f,$1b,$63,$88,$80 ; |IU...s.......c..|
		.BYTE	$49,$55,$10,$15,$0c,$73,$db,$bd,$f8,$c1,$e7,$8f,$1b,$63,$88,$80 ; |IU...s.......c..|
