;		.ORG	$96F0

		.BYTE	$06,$00,$07,$07,$fd,$fd,$11,$11,$11,$11,$11,$11,$07,$07,$11,$11 ; |................|
		.BYTE	$11,$00,$9e,$9e,$a4,$a4,$97,$97,$97,$97,$97,$97,$9e,$9e,$97,$97 ; |................|
		.BYTE	$97,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$aa,$aa,$f5,$5f,$ff,$ff,$ff,$ff,$ff,$f5,$5f,$ff,$ff,$ff,$ff,$ff ; |..._......_.....|
		.BYTE	$f5,$5f,$aa,$aa,$d5,$57,$ff,$ff,$ff,$ff,$ff,$d5,$57,$ff,$ff,$ff ; |._...W......W...|
		.BYTE	$ff,$ff,$d5,$57,$aa,$aa,$55,$55,$ff,$ff,$ff,$ff,$ff,$55,$55,$ff ; |...W..UU.....UU.|
		.BYTE	$ff,$ff,$ff,$ff,$55,$55,$aa,$a9,$57,$d5,$7f,$ff,$ff,$ff,$fd,$57 ; |....UU..W......W|
		.BYTE	$d5,$7f,$ff,$ff,$ff,$fd,$57,$d5,$6a,$a5,$5f,$f5,$5f,$ff,$ff,$ff ; |......W.j._._...|
		.BYTE	$f5,$5f,$f5,$5f,$ff,$ff,$ff,$f5,$5f,$f5,$5a,$a5,$7f,$fd,$5f,$ff ; |._._...._.Z..._.|
		.BYTE	$ff,$ff,$f5,$7f,$fd,$5f,$ff,$ff,$ff,$f5,$7f,$fd,$5a,$95,$7f,$fd ; |....._......Z...|
		.BYTE	$57,$ff,$ff,$ff,$d5,$7f,$fd,$57,$ff,$ff,$ff,$d5,$7f,$fd,$56,$95 ; |W......W......V.|
		.BYTE	$ff,$ff,$57,$ff,$ff,$ff,$d5,$ff,$ff,$57,$ff,$ff,$ff,$d5,$ff,$ff ; |..W......W......|
		.BYTE	$56,$55,$ff,$ff,$55,$ff,$ff,$ff,$55,$ff,$ff,$55,$ff,$ff,$ff,$55 ; |VU..U...U..U...U|
		.BYTE	$ff,$ff,$55,$56,$ff,$ff,$d5,$ff,$ff,$ff,$57,$ff,$ff,$d5,$ff,$ff ; |..UV......W.....|
		.BYTE	$ff,$57,$ff,$ff,$95,$56,$ff,$ff,$d5,$7f,$ff,$fd,$57,$ff,$ff,$d5 ; |.W...V......W...|
		.BYTE	$7f,$ff,$fd,$57,$ff,$ff,$95,$5a,$ff,$ff,$f5,$7f,$ff,$fd,$5f,$ff ; |...W...Z......_.|
		.BYTE	$ff,$f5,$7f,$ff,$fd,$5f,$ff,$ff,$a5,$5a,$ff,$ff,$f5,$5f,$ff,$f5 ; |....._...Z..._..|
		.BYTE	$5f,$ff,$ff,$f5,$5f,$ff,$f5,$5f,$ff,$ff,$a5,$6a,$ff,$ff,$fd,$5f ; |_..._.._...j..._|
		.BYTE	$ff,$f5,$7f,$ff,$ff,$fd,$5f,$ff,$f5,$7f,$ff,$ff,$a9,$6a,$ff,$ff ; |......_......j..|
		.BYTE	$fd,$57,$ff,$d5,$7f,$ff,$ff,$fd,$57,$ff,$d5,$7f,$ff,$ff,$a9,$aa ; |.W......W.......|
		.BYTE	$ff,$ff,$ff,$57,$ff,$d5,$ff,$ff,$ff,$ff,$57,$ff,$d5,$ff,$ff,$ff ; |...W......W.....|
		.BYTE	$aa,$aa,$ff,$ff,$ff,$55,$ff,$55,$ff,$ff,$ff,$ff,$55,$ff,$55,$ff ; |.....U.U....U.U.|
		.BYTE	$ff,$ff,$aa,$aa,$ff,$ff,$ff,$d5,$7d,$57,$ff,$ff,$ff,$ff,$d5,$7d ; |........}W.....}|
		.BYTE	$57,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$f5,$55,$5f,$ff,$ff,$ff,$ff ; |W.........U_....|
		.BYTE	$f5,$55,$5f,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$fd,$55,$7f,$ff,$ff ; |.U_.........U...|
		.BYTE	$ff,$ff,$fd,$55,$7f,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$55,$ff ; |...U..........U.|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$55,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff ; |.....U..........|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$af,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$fa,$af,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$fa,$af,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$fa,$af,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$fa,$af ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$fa,$af,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$fa,$af,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$fa,$af,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$fa,$af,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$fa,$af,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$fa,$af,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$fa,$af,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$fa,$ad,$7f,$ff,$ff,$d7,$ff,$ff,$fd,$7a ; |...............z|
		.BYTE	$a5,$5f,$ff,$ff,$55,$ff,$ff,$f5,$5a,$97,$d7,$ff,$fd,$7d,$7f,$ff ; |._..U...Z....}..|
		.BYTE	$d7,$d6,$5f,$f5,$ff,$f5,$ff,$5f,$ff,$5f,$f5,$5f,$f5,$ff,$f5,$ff ; |.._...._._._....|
		.BYTE	$5f,$ff,$5f,$f5,$6f,$fd,$7f,$d7,$ff,$d7,$fd,$7f,$f9,$6f,$fd,$7f ; |_._.o........o..|
		.BYTE	$d7,$ff,$d7,$fd,$7f,$f9,$af,$ff,$5f,$5f,$ff,$f5,$f5,$ff,$fa,$af ; |........__......|
		.BYTE	$ff,$5f,$5f,$ff,$f5,$f5,$ff,$fa,$af,$ff,$d5,$7f,$ff,$fd,$57,$ff ; |.__...........W.|
		.BYTE	$fa,$af,$ff,$f5,$ff,$ff,$ff,$5f,$ff,$fa,$af,$ff,$ff,$ff,$ff,$ff ; |......._........|
		.BYTE	$ff,$ff,$fa,$af,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$fa,$af,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$fa,$af,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$fa,$af,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$fa,$af,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$fa ; |................|
		.BYTE	$af,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$fa,$af,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$fa,$af,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$fa,$af,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$fa,$af,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$fa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$a0,$bf,$ff,$ff,$ff,$e0,$bf,$ff,$ff,$ff,$e0,$bf,$ff,$ff,$ff ; |................|
		.BYTE	$e0,$bf,$ff,$ff,$ff,$e0,$bf,$ff,$ff,$ff,$e0,$bf,$ff,$ff,$ff,$e0 ; |................|
		.BYTE	$97,$ff,$5f,$fd,$60,$7d,$fd,$f7,$f7,$d0,$7d,$fd,$f7,$f7,$d0,$bf ; |.._.`}....}.....|
		.BYTE	$77,$fd,$df,$e0,$bf,$df,$ff,$7f,$e0,$bf,$ff,$ff,$ff,$e0,$bf,$ff ; |w...............|
		.BYTE	$ff,$ff,$e0,$bf,$ff,$ff,$ff,$e0,$bf,$ff,$ff,$ff,$e0,$bf,$ff,$ff ; |................|
		.BYTE	$ff,$e0,$bf,$ff,$ff,$ff,$e0,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$00,$00,$00,$00,$00 ; |................|
		.BYTE	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ; |................|
		.BYTE	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$f5,$5f,$ff,$ff,$ff ; |............_...|
		.BYTE	$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$d5,$57,$ff ; |..............W.|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$55 ; |...............U|
		.BYTE	$55,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff ; |U...............|
		.BYTE	$fd,$54,$15,$7f,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff ; |.T..............|
		.BYTE	$ff,$ff,$f5,$50,$05,$5f,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff ; |...P._..........|
		.BYTE	$ff,$ff,$ff,$ff,$f5,$40,$01,$5f,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa ; |.....@._........|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$d5,$40,$01,$57,$ff,$ff,$ff,$ff,$ff,$ff ; |.......@.W......|
		.BYTE	$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$d5,$00,$00,$57,$ff,$ff,$ff,$ff ; |...........W....|
		.BYTE	$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$55,$00,$00,$55,$ff,$ff ; |..........U..U..|
		.BYTE	$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$54,$00,$00,$15 ; |............T...|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$54,$00 ; |..............T.|
		.BYTE	$00,$15,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$fd ; |................|
		.BYTE	$54,$00,$00,$15,$7f,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff ; |T...............|
		.BYTE	$ff,$fd,$50,$00,$00,$05,$7f,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff ; |..P.............|
		.BYTE	$ff,$ff,$ff,$fd,$50,$00,$00,$05,$7f,$ff,$ff,$ff,$ff,$ff,$aa,$aa ; |....P...........|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$f5,$50,$00,$00,$05,$5f,$ff,$ff,$ff,$ff,$ff ; |......P..._.....|
		.BYTE	$aa,$aa,$ff,$ff,$ff,$ff,$ff,$f5,$40,$00,$00,$01,$5f,$ff,$ff,$ff ; |........@..._...|
		.BYTE	$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$f5,$40,$00,$00,$01,$5f,$ff ; |..........@..._.|
		.BYTE	$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$f5,$40,$00,$00,$01 ; |............@...|
		.BYTE	$5f,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$f5,$5f,$ff,$ff,$ff,$d5,$40,$00 ; |_........_....@.|
		.BYTE	$00,$01,$57,$ff,$ff,$ff,$f5,$5f,$aa,$aa,$d5,$57,$ff,$ff,$ff,$d5 ; |..W...._...W....|
		.BYTE	$00,$00,$00,$00,$57,$ff,$ff,$ff,$d5,$57,$aa,$aa,$55,$55,$ff,$ff ; |....W....W..UU..|
		.BYTE	$ff,$d5,$00,$00,$00,$00,$57,$ff,$ff,$ff,$55,$55,$aa,$a9,$57,$d5 ; |......W...UU..W.|
		.BYTE	$7f,$ff,$ff,$d5,$00,$00,$00,$00,$57,$ff,$ff,$fd,$57,$d5,$6a,$a5 ; |........W...W.j.|
		.BYTE	$5f,$f5,$5f,$ff,$ff,$55,$00,$00,$00,$00,$55,$ff,$ff,$f5,$5f,$f5 ; |_._..U....U..._.|
		.BYTE	$5a,$a5,$7f,$fd,$5f,$ff,$ff,$54,$00,$00,$00,$00,$15,$ff,$ff,$f5 ; |Z..._..T........|
		.BYTE	$7f,$fd,$5a,$95,$7f,$fd,$57,$ff,$ff,$54,$00,$00,$00,$00,$15,$ff ; |..Z...W..T......|
		.BYTE	$ff,$d5,$7f,$fd,$56,$95,$ff,$ff,$57,$ff,$ff,$54,$00,$00,$00,$00 ; |....V...W..T....|
		.BYTE	$15,$ff,$ff,$d5,$ff,$ff,$56,$55,$ff,$ff,$55,$ff,$ff,$54,$00,$00 ; |......VU..U..T..|
		.BYTE	$00,$00,$15,$ff,$ff,$55,$ff,$ff,$55,$56,$ff,$ff,$d5,$ff,$ff,$54 ; |.....U..UV.....T|
		.BYTE	$00,$00,$00,$00,$15,$ff,$ff,$57,$ff,$ff,$95,$56,$ff,$ff,$d5,$7f ; |.......W...V....|
		.BYTE	$fd,$54,$00,$00,$00,$00,$15,$7f,$fd,$57,$ff,$ff,$95,$5a,$ff,$ff ; |.T.......W...Z..|
		.BYTE	$f5,$7f,$fd,$50,$00,$00,$00,$00,$05,$7f,$fd,$5f,$ff,$ff,$a5,$5a ; |...P......._...Z|
		.BYTE	$ff,$ff,$f5,$5f,$fd,$50,$00,$00,$00,$00,$05,$7f,$f5,$5f,$ff,$ff ; |..._.P......._..|
		.BYTE	$a5,$6a,$ff,$ff,$fd,$5f,$fd,$50,$00,$00,$00,$00,$05,$7f,$f5,$7f ; |.j..._.P........|
		.BYTE	$ff,$ff,$a9,$6a,$ff,$ff,$fd,$57,$fd,$50,$00,$00,$00,$00,$05,$7f ; |...j...W.P......|
		.BYTE	$d5,$7f,$ff,$ff,$a9,$aa,$ff,$ff,$ff,$57,$fd,$50,$00,$00,$00,$00 ; |.........W.P....|
		.BYTE	$05,$7f,$d5,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$55,$f5,$50,$00,$00 ; |...........U.P..|
		.BYTE	$00,$00,$05,$5f,$55,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$d5,$75,$40 ; |..._U.........u@|
		.BYTE	$00,$00,$00,$00,$01,$5d,$57,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$f5 ; |.....]W.........|
		.BYTE	$55,$40,$00,$00,$00,$00,$01,$55,$5f,$ff,$ff,$ff,$aa,$aa,$ff,$ff ; |U@.....U_.......|
		.BYTE	$ff,$fd,$55,$40,$00,$00,$00,$00,$01,$55,$7f,$ff,$ff,$ff,$aa,$aa ; |..U@.....U......|
		.BYTE	$ff,$ff,$ff,$ff,$55,$40,$00,$00,$00,$00,$01,$55,$ff,$ff,$ff,$ff ; |....U@.....U....|
		.BYTE	$aa,$aa,$ff,$ff,$ff,$ff,$f5,$40,$00,$00,$00,$00,$01,$5f,$ff,$ff ; |.......@....._..|
		.BYTE	$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$d5,$40,$00,$00,$00,$00,$01,$57 ; |.........@.....W|
		.BYTE	$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$d5,$00,$00,$00,$00,$00 ; |................|
		.BYTE	$00,$57,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$d5,$00,$00,$00 ; |.W..............|
		.BYTE	$00,$00,$00,$57,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$d5,$00 ; |...W............|
		.BYTE	$00,$00,$00,$00,$00,$57,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff ; |.....W..........|
		.BYTE	$d5,$00,$00,$00,$00,$00,$00,$57,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff ; |.......W........|
		.BYTE	$ff,$ff,$d5,$00,$00,$00,$00,$00,$00,$57,$ff,$ff,$ff,$ff,$aa,$aa ; |.........W......|
		.BYTE	$ff,$ff,$ff,$ff,$55,$00,$00,$00,$00,$00,$00,$55,$ff,$ff,$ff,$ff ; |....U......U....|
		.BYTE	$aa,$aa,$ff,$ff,$ff,$ff,$54,$00,$00,$00,$00,$00,$00,$15,$ff,$ff ; |......T.........|
		.BYTE	$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$54,$00,$00,$00,$00,$00,$00,$15 ; |........T.......|
		.BYTE	$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$54,$00,$00,$00,$00,$00 ; |..........T.....|
		.BYTE	$00,$15,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$54,$00,$00,$00 ; |............T...|
		.BYTE	$00,$00,$00,$15,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$54,$00 ; |..............T.|
		.BYTE	$00,$00,$00,$00,$00,$15,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$fd ; |................|
		.BYTE	$54,$00,$00,$00,$00,$00,$00,$15,$7f,$ff,$ff,$ff,$aa,$aa,$ff,$ff ; |T...............|
		.BYTE	$ff,$fd,$50,$00,$00,$00,$00,$00,$00,$05,$7f,$ff,$ff,$ff,$aa,$aa ; |..P.............|
		.BYTE	$ff,$ff,$ff,$fd,$50,$00,$00,$00,$00,$00,$00,$05,$7f,$ff,$ff,$ff ; |....P...........|
		.BYTE	$aa,$aa,$ff,$ff,$ff,$fd,$50,$00,$00,$00,$00,$00,$00,$05,$7f,$ff ; |......P.........|
		.BYTE	$ff,$ff,$aa,$aa,$ff,$ff,$ff,$f5,$50,$00,$00,$00,$00,$00,$00,$05 ; |........P.......|
		.BYTE	$5f,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$f5,$50,$00,$00,$00,$00,$00 ; |_.........P.....|
		.BYTE	$00,$05,$5f,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$f5,$50,$00,$00,$00 ; |.._.........P...|
		.BYTE	$00,$00,$00,$05,$5f,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$d5,$40,$00 ; |...._.........@.|
		.BYTE	$00,$00,$00,$00,$00,$01,$57,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$d5 ; |......W.........|
		.BYTE	$40,$00,$00,$00,$00,$00,$00,$01,$57,$ff,$ff,$ff,$aa,$aa,$ff,$ff ; |@.......W.......|
		.BYTE	$ff,$55,$40,$00,$00,$00,$00,$00,$00,$01,$55,$ff,$ff,$ff,$aa,$aa ; |.U@.......U.....|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$af,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$fa,$af,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$fa,$af,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$fa,$af,$ff,$ff,$ff ; |................|
		.BYTE	$d7,$ff,$ff,$ff,$fa,$af,$ff,$ff,$ff,$55,$ff,$ff,$ff,$fa,$af,$ff ; |.........U......|
		.BYTE	$ff,$fd,$41,$7f,$ff,$ff,$fa,$af,$ff,$ff,$f5,$00,$5f,$ff,$ff,$fa ; |..A........._...|
		.BYTE	$af,$ff,$ff,$f5,$00,$5f,$ff,$ff,$fa,$af,$ff,$ff,$f5,$00,$5f,$ff ; |....._........_.|
		.BYTE	$ff,$fa,$af,$ff,$ff,$d4,$00,$17,$ff,$ff,$fa,$af,$ff,$ff,$d4,$00 ; |................|
		.BYTE	$17,$ff,$ff,$fa,$af,$ff,$ff,$d4,$00,$17,$ff,$ff,$fa,$ad,$7f,$ff ; |................|
		.BYTE	$50,$00,$05,$ff,$fd,$7a,$a5,$5f,$ff,$50,$00,$05,$ff,$f5,$5a,$97 ; |P....z._.P....Z.|
		.BYTE	$d7,$ff,$50,$00,$05,$ff,$d7,$d6,$5f,$f5,$ff,$50,$00,$05,$ff,$5f ; |..P....._..P..._|
		.BYTE	$f5,$5f,$f5,$ff,$50,$00,$05,$ff,$5f,$f5,$6f,$fd,$7d,$40,$00,$01 ; |._..P..._.o.}@..|
		.BYTE	$7d,$7f,$f9,$6f,$fd,$7d,$40,$00,$01,$7d,$7f,$f9,$af,$ff,$5d,$40 ; |}..o.}@..}....]@|
		.BYTE	$00,$01,$75,$ff,$fa,$af,$ff,$5d,$40,$00,$01,$75,$ff,$fa,$af,$ff ; |..u....]@..u....|
		.BYTE	$d5,$40,$00,$01,$57,$ff,$fa,$af,$ff,$d5,$40,$00,$01,$57,$ff,$fa ; |.@..W.....@..W..|
		.BYTE	$af,$ff,$f5,$00,$00,$00,$5f,$ff,$fa,$af,$ff,$f5,$00,$00,$00,$5f ; |......_........_|
		.BYTE	$ff,$fa,$af,$ff,$f5,$00,$00,$00,$5f,$ff,$fa,$af,$ff,$f5,$00,$00 ; |........_.......|
		.BYTE	$00,$5f,$ff,$fa,$af,$ff,$f5,$00,$00,$00,$5f,$ff,$fa,$af,$ff,$d4 ; |._........_.....|
		.BYTE	$00,$00,$00,$17,$ff,$fa,$af,$ff,$d4,$00,$00,$00,$17,$ff,$fa,$af ; |................|
		.BYTE	$ff,$d4,$00,$00,$00,$17,$ff,$fa,$af,$ff,$d4,$00,$00,$00,$17,$ff ; |................|
		.BYTE	$fa,$af,$ff,$50,$00,$00,$00,$05,$ff,$fa,$af,$ff,$50,$00,$00,$00 ; |...P........P...|
		.BYTE	$05,$ff,$fa,$aa,$aa,$aa,$aa,$a0,$bf,$ff,$ff,$ff,$e0,$bf,$ff,$ff ; |................|
		.BYTE	$ff,$e0,$bf,$ff,$5f,$ff,$e0,$bf,$fd,$57,$ff,$e0,$bf,$fd,$07,$ff ; |...._....W......|
		.BYTE	$e0,$bf,$f5,$05,$ff,$e0,$97,$f4,$01,$fd,$60,$7d,$f4,$01,$f7,$d0 ; |..........`}....|
		.BYTE	$7d,$f4,$01,$f7,$d0,$bf,$74,$01,$df,$e0,$bf,$54,$01,$5f,$e0,$bf ; |}.....t....T._..|
		.BYTE	$d0,$00,$7f,$e0,$bf,$d0,$00,$7f,$e0,$bf,$d0,$00,$7f,$e0,$bf,$50 ; |...............P|
		.BYTE	$00,$5f,$e0,$bf,$40,$00,$1f,$e0,$bf,$40,$00,$1f,$e0,$ff,$ff,$ff ; |._..@....@......|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$f5,$5f,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff ; |.._.............|
		.BYTE	$ff,$ff,$ff,$d5,$57,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff ; |....W...........|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$55,$55,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa ; |.....UU.........|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$fd,$56,$95,$7f,$ff,$ff,$ff,$ff,$ff,$ff ; |.......V........|
		.BYTE	$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$f5,$5a,$a5,$5f,$ff,$ff,$ff,$ff ; |.........Z._....|
		.BYTE	$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$f5,$6a,$a9,$5f,$ff,$ff ; |...........j._..|
		.BYTE	$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$d5,$6a,$a9,$57 ; |.............j.W|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff,$d5,$aa ; |................|
		.BYTE	$aa,$57,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$ff ; |.W..............|
		.BYTE	$55,$aa,$aa,$55,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff ; |U..U............|
		.BYTE	$ff,$ff,$56,$aa,$aa,$95,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff ; |..V.............|
		.BYTE	$ff,$ff,$ff,$ff,$56,$aa,$aa,$95,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$aa ; |....V...........|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$fd,$56,$aa,$aa,$95,$7f,$ff,$ff,$ff,$ff,$ff ; |......V.........|
		.BYTE	$aa,$aa,$ff,$ff,$ff,$ff,$ff,$fd,$5a,$aa,$aa,$a5,$7f,$ff,$ff,$ff ; |........Z.......|
		.BYTE	$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$fd,$5a,$aa,$aa,$a5,$7f,$ff ; |..........Z.....|
		.BYTE	$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$f5,$5a,$aa,$aa,$a5 ; |............Z...|
		.BYTE	$5f,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$f5,$6a,$aa ; |_.............j.|
		.BYTE	$aa,$a9,$5f,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$f5 ; |.._.............|
		.BYTE	$6a,$aa,$aa,$a9,$5f,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff ; |j..._...........|
		.BYTE	$ff,$f5,$6a,$aa,$aa,$a9,$5f,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$f5,$5f ; |..j..._........_|
		.BYTE	$ff,$ff,$ff,$d5,$6a,$aa,$aa,$a9,$57,$ff,$ff,$ff,$f5,$5f,$aa,$aa ; |....j...W...._..|
		.BYTE	$d5,$57,$ff,$ff,$ff,$d5,$aa,$aa,$aa,$aa,$57,$ff,$ff,$ff,$d5,$57 ; |.W........W....W|
		.BYTE	$aa,$aa,$55,$55,$ff,$ff,$ff,$d5,$aa,$aa,$aa,$aa,$57,$ff,$ff,$ff ; |..UU........W...|
		.BYTE	$55,$55,$aa,$a9,$57,$d5,$7f,$ff,$ff,$d5,$aa,$aa,$aa,$aa,$57,$ff ; |UU..W.........W.|
		.BYTE	$ff,$fd,$57,$d5,$6a,$a5,$5f,$f5,$5f,$ff,$ff,$55,$aa,$aa,$aa,$aa ; |..W.j._._..U....|
		.BYTE	$55,$ff,$ff,$f5,$5f,$f5,$5a,$a5,$7f,$fd,$5f,$ff,$ff,$56,$aa,$aa ; |U..._.Z..._..V..|
		.BYTE	$aa,$aa,$95,$ff,$ff,$f5,$7f,$fd,$5a,$95,$7f,$fd,$57,$ff,$ff,$56 ; |........Z...W..V|
		.BYTE	$aa,$aa,$aa,$aa,$95,$ff,$ff,$d5,$7f,$fd,$56,$95,$ff,$ff,$57,$ff ; |..........V...W.|
		.BYTE	$ff,$56,$aa,$aa,$aa,$aa,$95,$ff,$ff,$d5,$ff,$ff,$56,$55,$ff,$ff ; |.V..........VU..|
		.BYTE	$55,$ff,$ff,$56,$aa,$aa,$aa,$aa,$95,$ff,$ff,$55,$ff,$ff,$55,$56 ; |U..V.......U..UV|
		.BYTE	$ff,$ff,$d5,$ff,$ff,$56,$aa,$aa,$aa,$aa,$95,$ff,$ff,$57,$ff,$ff ; |.....V.......W..|
		.BYTE	$95,$56,$ff,$ff,$d5,$7f,$ff,$56,$aa,$aa,$aa,$aa,$95,$ff,$fd,$57 ; |.V.....V.......W|
		.BYTE	$ff,$ff,$95,$5a,$ff,$ff,$f5,$7f,$ff,$56,$aa,$aa,$aa,$aa,$95,$ff ; |...Z.....V......|
		.BYTE	$fd,$5f,$ff,$ff,$a5,$5a,$ff,$ff,$f5,$5f,$ff,$56,$aa,$aa,$aa,$aa ; |._...Z..._.V....|
		.BYTE	$95,$ff,$f5,$5f,$ff,$ff,$a5,$6a,$ff,$ff,$fd,$5f,$ff,$56,$aa,$aa ; |..._...j..._.V..|
		.BYTE	$aa,$aa,$95,$ff,$f5,$7f,$ff,$ff,$a9,$6a,$ff,$ff,$fd,$57,$ff,$56 ; |.........j...W.V|
		.BYTE	$aa,$aa,$aa,$aa,$95,$ff,$d5,$7f,$ff,$ff,$a9,$aa,$ff,$ff,$ff,$57 ; |...............W|
		.BYTE	$ff,$56,$aa,$aa,$aa,$aa,$95,$ff,$d5,$ff,$ff,$ff,$aa,$aa,$ff,$ff ; |.V..............|
		.BYTE	$ff,$55,$ff,$55,$aa,$aa,$aa,$aa,$55,$ff,$55,$ff,$ff,$ff,$aa,$aa ; |.U.U....U.U.....|
		.BYTE	$ff,$ff,$ff,$d5,$7d,$55,$aa,$aa,$aa,$aa,$55,$7d,$57,$ff,$ff,$ff ; |....}U....U}W...|
		.BYTE	$aa,$aa,$ff,$ff,$ff,$f5,$55,$55,$aa,$aa,$aa,$aa,$55,$55,$5f,$ff ; |......UU....UU_.|
		.BYTE	$ff,$ff,$aa,$aa,$ff,$ff,$ff,$fd,$55,$55,$aa,$aa,$aa,$aa,$55,$55 ; |........UU....UU|
		.BYTE	$7f,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$55,$d5,$aa,$aa,$aa,$aa ; |..........U.....|
		.BYTE	$57,$55,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$d5,$aa,$aa ; |WU..............|
		.BYTE	$aa,$aa,$57,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$d5 ; |..W.............|
		.BYTE	$aa,$aa,$aa,$aa,$57,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff ; |....W...........|
		.BYTE	$ff,$d5,$6a,$aa,$aa,$a9,$57,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff ; |..j...W.........|
		.BYTE	$ff,$ff,$ff,$f5,$6a,$aa,$aa,$a9,$5f,$ff,$ff,$ff,$ff,$ff,$aa,$aa ; |....j..._.......|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$f5,$6a,$aa,$aa,$a9,$5f,$ff,$ff,$ff,$ff,$ff ; |......j..._.....|
		.BYTE	$aa,$aa,$ff,$ff,$ff,$ff,$ff,$f5,$6a,$aa,$aa,$a9,$5f,$ff,$ff,$ff ; |........j..._...|
		.BYTE	$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$f5,$6a,$aa,$aa,$a9,$5f,$ff ; |..........j..._.|
		.BYTE	$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$f5,$6a,$aa,$aa,$a9 ; |............j...|
		.BYTE	$5f,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$f5,$6a,$aa ; |_.............j.|
		.BYTE	$aa,$a9,$5f,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$f5 ; |.._.............|
		.BYTE	$6a,$aa,$aa,$a9,$5f,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff ; |j..._...........|
		.BYTE	$ff,$f5,$6a,$aa,$aa,$a9,$5f,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff ; |..j..._.........|
		.BYTE	$ff,$ff,$ff,$f5,$6a,$aa,$aa,$a9,$5f,$ff,$ff,$ff,$ff,$ff,$aa,$aa ; |....j..._.......|
		.BYTE	$ff,$ff,$ff,$ff,$ff,$f5,$6a,$aa,$aa,$a9,$5f,$ff,$ff,$ff,$ff,$ff ; |......j..._.....|
		.BYTE	$aa,$aa,$ff,$ff,$ff,$ff,$ff,$d5,$6a,$aa,$aa,$a9,$57,$ff,$ff,$ff ; |........j...W...|
		.BYTE	$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$d5,$aa,$aa,$aa,$aa,$57,$ff ; |..............W.|
		.BYTE	$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$d5,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$57,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$d5,$aa,$aa ; |W...............|
		.BYTE	$aa,$aa,$57,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$ff,$55 ; |..W............U|
		.BYTE	$aa,$aa,$aa,$aa,$55,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff ; |....U...........|
		.BYTE	$ff,$56,$aa,$aa,$aa,$aa,$95,$ff,$ff,$ff,$ff,$ff,$aa,$aa,$ff,$ff ; |.V..............|
		.BYTE	$ff,$ff,$ff,$56,$aa,$aa,$aa,$aa,$95,$ff,$ff,$ff,$ff,$ff,$aa,$aa ; |...V............|
		.BYTE	$ff,$ff,$ff,$ff,$fd,$56,$aa,$aa,$aa,$aa,$95,$7f,$ff,$ff,$ff,$ff ; |.....V..........|
		.BYTE	$aa,$aa,$ff,$ff,$ff,$ff,$fd,$5a,$aa,$aa,$aa,$aa,$a5,$7f,$ff,$ff ; |.......Z........|
		.BYTE	$ff,$ff,$aa,$aa,$ff,$ff,$ff,$ff,$f5,$5a,$aa,$aa,$aa,$aa,$a5,$5f ; |.........Z....._|
		.BYTE	$ff,$ff,$ff,$ff,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa ; |................|
		.BYTE	$aa,$aa,$aa,$aa,$aa,$aa,$aa,$af,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$fa ; |................|
		.BYTE	$af,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$fa,$af,$ff,$ff,$ff,$ff,$ff,$ff ; |................|
		.BYTE	$ff,$fa,$af,$ff,$ff,$ff,$d7,$ff,$ff,$ff,$fa,$af,$ff,$ff,$ff,$55 ; |...............U|
		.BYTE	$ff,$ff,$ff,$fa,$af,$ff,$ff,$fd,$69,$7f,$ff,$ff,$fa,$af,$ff,$ff ; |........i.......|
		.BYTE	$f5,$aa,$5f,$ff,$ff,$fa,$af,$ff,$ff,$f5,$aa,$5f,$ff,$ff,$fa,$af ; |.._........_....|
		.BYTE	$ff,$ff,$d6,$aa,$97,$ff,$ff,$fa,$af,$ff,$ff,$d6,$aa,$97,$ff,$ff ; |................|
		.BYTE	$fa,$af,$ff,$ff,$d6,$aa,$97,$ff,$ff,$fa,$af,$ff,$ff,$5a,$aa,$a5 ; |.............Z..|
		.BYTE	$ff,$ff,$fa,$ad,$7f,$ff,$5a,$aa,$a5,$ff,$fd,$7a,$a5,$5f,$ff,$5a ; |......Z....z._.Z|
		.BYTE	$aa,$a5,$ff,$f5,$5a,$97,$d7,$ff,$5a,$aa,$a5,$ff,$d7,$d6,$5f,$f5 ; |....Z...Z....._.|
		.BYTE	$fd,$6a,$aa,$a9,$7f,$5f,$f5,$5f,$f5,$fd,$6a,$aa,$a9,$7f,$5f,$f5 ; |.j..._._..j..._.|
		.BYTE	$6f,$fd,$7d,$6a,$aa,$a9,$7d,$7f,$f9,$6f,$fd,$7d,$6a,$aa,$a9,$7d ; |o.}j..}..o.}j..}|
		.BYTE	$7f,$f9,$af,$ff,$5d,$6a,$aa,$a9,$75,$ff,$fa,$af,$ff,$5f,$5a,$aa ; |....]j..u...._Z.|
		.BYTE	$a5,$f5,$ff,$fa,$af,$ff,$d5,$5a,$aa,$a5,$57,$ff,$fa,$af,$ff,$f5 ; |.......Z..W.....|
		.BYTE	$5a,$aa,$a5,$5f,$ff,$fa,$af,$ff,$ff,$5a,$aa,$a5,$ff,$ff,$fa,$af ; |Z.._.....Z......|
		.BYTE	$ff,$ff,$d6,$aa,$97,$ff,$ff,$fa,$af,$ff,$ff,$d6,$aa,$97,$ff,$ff ; |................|
		.BYTE	$fa,$af,$ff,$ff,$d6,$aa,$97,$ff,$ff,$fa,$af,$ff,$ff,$d6,$aa,$97 ; |................|
		.BYTE	$ff,$ff,$fa,$af,$ff,$ff,$d6,$aa,$97,$ff,$ff,$fa,$af,$ff,$ff,$5a ; |...............Z|
		.BYTE	$aa,$a5,$ff,$ff,$fa,$af,$ff,$ff,$5a,$aa,$a5,$ff,$ff,$fa,$af,$ff ; |........Z.......|
		.BYTE	$ff,$5a,$aa,$a5,$ff,$ff,$fa,$af,$ff,$fd,$6a,$aa,$a9,$7f,$ff,$fa ; |.Z........j.....|
		.BYTE	$af,$ff,$fd,$6a,$aa,$a9,$7f,$ff,$fa,$aa,$aa,$aa,$aa,$a0,$bf,$ff ; |...j............|
		.BYTE	$ff,$ff,$e0,$bf,$ff,$ff,$ff,$e0,$bf,$ff,$5f,$ff,$e0,$bf,$fd,$a7 ; |.........._.....|
		.BYTE	$ff,$e0,$bf,$fd,$a7,$ff,$e0,$bf,$f6,$a9,$ff,$e0,$97,$f6,$a9,$fd ; |................|
		.BYTE	$60,$7d,$f6,$a9,$f7,$d0,$7d,$f6,$a9,$f7,$d0,$bf,$76,$a9,$df,$e0 ; |`}....}.....v...|
		.BYTE	$bf,$d6,$a9,$7f,$e0,$bf,$f5,$a5,$ff,$e0,$bf,$f5,$a5,$ff,$e0,$bf ; |................|
		.BYTE	$f6,$a9,$ff,$e0,$bf,$f6,$a9,$ff,$e0,$bf,$da,$aa,$7f,$e0,$bf,$da ; |................|
		.BYTE	$aa,$7f,$e0,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ; |................|
		.BYTE	$4a,$05,$10,$15,$9e,$6c,$47,$b6,$75,$7d,$09,$d1,$60,$6f,$e2,$95 ; |J....lG.u}..`o..|
		.BYTE	$4a,$05,$10,$15,$9e,$3c,$17,$b6,$75,$7d,$09,$d1,$60,$6f,$e2,$95 ; |J....<..u}..`o..|
		.BYTE	$4a,$05,$10,$15,$9e,$6c,$47,$b6,$75,$7d,$09,$d1,$60,$6f,$e2,$95 ; |J....lG.u}..`o..|
		.BYTE	$4a,$05,$10,$15,$9e,$6c,$47,$b6,$75,$7d,$09,$d1,$60,$6f,$e2,$95 ; |J....lG.u}..`o..|
		.BYTE	$4a,$05,$10,$15,$9e,$6c,$47,$b6,$75,$7d,$09,$d1,$60,$6f,$e2,$95 ; |J....lG.u}..`o..|
		.BYTE	$4a,$05,$10,$15,$9e,$6c,$47,$b6,$75,$7d,$09,$d1,$60,$6f,$e2,$95 ; |J....lG.u}..`o..|
		.BYTE	$4a,$05,$10,$15,$9e,$6c,$47,$b6,$75,$7d,$09,$d1,$60,$6f,$e2,$95 ; |J....lG.u}..`o..|
